name = "xugou-backend"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

# 添加定时触发器，每分钟执行一次监控检查
[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "d1"
database_id = "398e9405-a148-42b6-b99a-8eaf52ed948e"

[version_metadata]
binding = "CF_VERSION_METADATA"
